name: bad_birdie
description: 'A Flutter app for badminton training'
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ^3.10.4

dependencies:
  audioplayers: ^6.6.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_tts: ^4.2.2
  google_fonts: ^6.2.1
  intl: any
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  sleek_circular_slider: ^2.0.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/sounds/
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/birdie_dark.png"
  min_sdk_android: 21
  adaptive_icon_background: "#582c82"
  adaptive_icon_foreground: "assets/images/birdie.png"

flutter_native_splash:
  color: "#0c0c11"
  image: assets/images/logo.png
  image_android: assets/images/birdie.png
  color_dark: "#0c0c11"
  image_dark: assets/images/logo.png
  image_dark_android: assets/images/birdie.png
  android_12:
    color: "#0c0c11"
    image: assets/images/birdie.png
    icon_background_color: "#0c0c11"
  web: false
